Repository dunia07/SAP005-burger-queen, pull requests merged in 2021-03, with the labels that each got.

#36 deletando produto do resumo, somando só o último item adicionado
  src/components/cardapio/breakfast.js
  src/image/lixeira.png
  src/pages/orderMenu/orderMenu.js
  src/pages/pendingOrders/pendingOrders.js
Labels: Sprint 3

#37 corrigindo erro
  src/components/navbar/hallNavbar.js
  src/pages/orderMenu/orderMenu.js
  src/pages/pendingOrders/pendingOrders.js
Labels: Sprint 3

#39 pegando pedidos da api e mostrando na cozinha
  src/components/cardapio/breakfast.js
  src/pages/pendingOrders/pendingOrders.js
Labels: Sprint 4

#40 alterando o status
  src/components/cardapio/breakfast.js
  src/pages/pendingOrders/pendingOrders.js
Labels: Sprint 4

#41 Fazendo pedidos no menu allday, atualizando status e mostrando na pág…
  src/components/cardapio/allday.js
  src/components/cardapio/breakfast.js
  src/components/navbar/kitchenNavbar.js
  src/pages/finalizedOrders/finalizedOrders.js
  src/pages/pendingOrders/pendingOrders.js
  src/pages/readyOrders/readyOrders.js
Labels: Sprint 4

#43 limpando página ao enviar o pedido
  src/components/cardapio/allday.js
  src/components/cardapio/breakfast.js
  src/pages/finalizedOrders/finalizedOrders.js
  src/pages/pendingOrders/pendingOrders.js
  src/pages/readyOrders/readyOrders.js
Labels: Sprint 4

#44 Feature/desabilitarclick/refatoraçãofunções
  src/components/cardapio/allday.js
  src/components/cardapio/breakfast.js
  src/pages/pendingOrders/pendingOrders.js
Labels: Sprint 4

#46 style(pages): estilização da navbar, menu select, e cardápio
  src/App.css
  src/App.js
  src/components/cardapio/allday.js
  src/components/cardapio/breakfast.js
  src/components/header/innerHeader.js
  src/components/input.js
  src/components/navbar/navbar.js
  src/pages/orderMenu/orderMenu.js
Labels: Sprint 4

#47 resolução de conflito
  src/components/cardapio/allday.js
  src/components/cardapio/breakfast.js
Labels: Sprint 4

#48 correção de erros do key
  public/index.html
  public/manifest.json
  public/robots.txt
  src/components/cardapio/allday.js
  src/components/cardapio/breakfast.js
  src/pages/finalizedOrders/finalizedOrders.js
  src/pages/pendingOrders/pendingOrders.js
  src/pages/readyOrders/readyOrders.js
Labels: Sprint 4

#49 style(order-menu): estilização da página de Menu Pedidos
  src/App.css
  src/components/cardapio/allday.js
  src/image/lixeira.png
  src/pages/orderMenu/orderMenu.js
Labels: CSS, Sprint 4

#59 readme
  README.md
  inicioLogin.PNG
  src/image/gitHub_projects.png
  src/image/historia_usuario_01.png
  src/image/historia_usuario_02.png
  src/image/layout01.jpeg
  src/image/layout02.jpeg
Labels: Sprint 4

#60 style(app): estilização do aplicativo
  src/App.css
  src/components/cardapio/allday.js
  src/components/cardapio/breakfast.js
  src/pages/finalizedOrders/finalizedOrders.js
  src/pages/orderMenu/orderMenu.js
  src/pages/pendingOrders/pendingOrders.js
  src/pages/readyOrders/readyOrders.js
Labels: Sprint 4

#61 style(app): ajuste card de pedidos
  src/App.css
  src/pages/finalizedOrders/finalizedOrders.js
  src/pages/pendingOrders/pendingOrders.js
  src/pages/readyOrders/readyOrders.js
Labels: CSS, Sprint 4

#63 correções imagens readme
  README.md
  src/image/gitHub_projects.jpeg
  src/image/gitHub_projects.png
  src/image/historia01.jpeg
  src/image/historia02.jpeg
  src/image/historia_usuario_01.png
  src/image/historia_usuario_02.png
  src/image/inicioLogin.PNG
  src/image/login.jpeg
  src/image/menupedidos.jpeg
  src/image/menupedidos2.jpeg
  src/image/pedidosfinalizados.jpeg
  src/image/pedidospendentes.jpeg
  src/image/pedidosprontos.jpeg
Labels: Sprint 4
